import '../../../core/helpers/app_shared_methods.dart';
import '../../../core/network/utils/api_service.dart';
import '../../../core/network/utils/dio_factory.dart';
import '../../../core/widgets/app_progress_loading/progress_controller.dart';
import '../../../core/widgets/app_progress_loading/progress_loading.dart';
import '../../../features/auth/login/controller/login_repo.dart';
import '../../../features/auth/verification_code/controller/verification_code_repo.dart';
import 'package:dio/dio.dart';
import 'package:get/get.dart';
import '../../features/ad_details/controller/ad_details_repo.dart';
import '../../features/add_a_delivery_address/controller/add_a_delivery_repo.dart';
import '../../features/advertisement_summary/controller/advertisement_summary_repo.dart';
import '../../features/all_ads/controller/all_ads_repo.dart';
import '../../features/auth/register/controller/register_repo.dart';
import '../../features/auth/terms_and_conditions/controller/app_info_repo.dart';
import '../../features/booking_date/controller/booking_data_repo.dart';
import '../../features/captain_joins/controller/captain_joins_repo.dart';
import '../../features/choose_the_service/controller/choose_the_service_repo.dart';
import '../../features/choose_the_service/controller/order_data_controller.dart';
import '../../features/delete_my_account/controller/delete_account_repo.dart';
import '../../features/direct_suppor_map/controller/direct_support_map_repo.dart';
import '../../features/document/controller/document_repo.dart';
import '../../features/home_page/controller/home_repo.dart';
import '../../features/item_ad_details/controller/item_ad_details_repo.dart';
import '../../features/my_ad_pay_ment/controller/my_ad_pay_ment_repo.dart';
import '../../features/my_ads/controller/my_ads_repo.dart';
import '../../features/my_ads_details/controller/my_ads_details_repo.dart';
import '../../features/my_offer_ad_details/controller/offer_details_repo.dart';
import '../../features/notifications/controller/notifications_repo.dart';
import '../../features/personal_data/controller/personal_data_repo.dart';
import '../../features/price_details/controller/price_details_repo.dart';
import '../../features/price_details_review/controller/rating_repo.dart';
import '../../features/profile/controller/profile_repo.dart';
import '../../features/report_a_problem/controller/report_problem_repo.dart';
import '../../features/report_a_problem_chat_support/controller/chat_technical_support_repo.dart';
import '../../features/saved_delivery_addresses/controller/saved_delivery_addresses_repo.dart';
import '../../features/update_mobile_number/controller/update_mobile_repo.dart';
import '../../features/user_info/controller/user_info_repo.dart';
import '../../features/ver_code_mobile/controller/ver_code_repo.dart';
import '../../features/wallet/controller/wallet_repo.dart';
import '../../features/we_are_here_to_help/controller/faq_repo.dart';
// import '../../features/we_are_here_to_help/controller/faq_repo.dart';

Future<void> setupGetX() async {
  Get.put(AppSharedMethods());
  Dio dio = await DioFactory.getDio();
  Get.put(ApiService(dio));
  Get.put(ProgressController());
  Get.put(ProgressLoading());
  Get.put(OrderDataController());
  Get.put(LoginRepo(Get.find<ApiService>()));
  Get.put(VerificationCodeRepo(Get.find<ApiService>()));
  Get.put(OrdersRepo(Get.find<ApiService>()));
  Get.put(AddADeliveryRepo(Get.find<ApiService>()));
  Get.put(AdvertisementSummaryRepo(Get.find<ApiService>()));
  Get.put(AllAdsRepo(Get.find<ApiService>()));
  Get.put(RegisterRepo(Get.find<ApiService>()));
  Get.put(AppInfoRepo(Get.find<ApiService>()));
  Get.put(BookingDataRepo(Get.find<ApiService>()));
  Get.put(CaptainJoinsRepo(Get.find<ApiService>()));
  Get.put(ChooseTheServiceRepo(Get.find<ApiService>()));
  Get.put(DeleteAccountRepo(Get.find<ApiService>()));
  Get.put(DirectSupportMapRepo(Get.find<ApiService>()));
  Get.put(DocumentRepo(Get.find<ApiService>()));
  Get.put(HomeRepo(Get.find<ApiService>()));
  Get.put(ItemAdDetailsRepo(Get.find<ApiService>()));
  Get.put(MyAdPayMentRepo(Get.find<ApiService>()));
  Get.put(MyAdsRepo(Get.find<ApiService>()));
  Get.put(MyAdsDetailsRepo(Get.find<ApiService>()));
  Get.put(OfferDetailsRepo(Get.find<ApiService>()));
  Get.put(NotificationsRepo(Get.find<ApiService>()));
  Get.put(PersonalDataRepo(Get.find<ApiService>()));
  Get.put(PriceDetailsRepo(Get.find<ApiService>()));
  Get.put(RatingRepo(Get.find<ApiService>()));
  Get.put(ProfileRepo(Get.find<ApiService>()));
  Get.put(ReportProblemRepo(Get.find<ApiService>()));
  Get.put(ChatTechnicalSupportRepo(Get.find<ApiService>()));
  Get.put(SavedDeliveryAddressesRepo(Get.find<ApiService>()));
  Get.put(UpdateMobileRepo(Get.find<ApiService>()));
  Get.put(UserInfoRepo(Get.find<ApiService>()));
  Get.put(VerCodeRepo(Get.find<ApiService>()));
  Get.put(WalletRepo(Get.find<ApiService>()));
  Get.put(FaqRepo(Get.find<ApiService>()));
}
